name: Metrics
on:
  # Aktualizuj co godzinę
  schedule: [{cron: "0 * * * *"}]
  # Pozwól na ręczne uruchomienie
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Token
          token: ${{ secrets.METRICS_TOKEN }}

          # Podstawowe opcje
          user: DominikPalacz
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Warsaw
          
          # ZAMIANA: Usunięto zepsuty Skyline, dodano Isocalendar (zielone klocki 3D)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
